// Created uCompressHaar.exe
// Haar cascade types
  TocvHaarCascadeType =
  (
hcEye,
hcEyeTreeEyeglasses,
hcFrontalfaceAlt,
hcFrontalfaceAlt2,
hcFrontalfaceAltTree,
hcFrontalfaceDefault,
hcFullbody,
hcLefteye2splits,
hcLowerbody,
hcMcsEyepairBig,
hcMcsEyepairSmall,
hcMcsLeftear,
hcMcsLefteye,
hcMcsMouth,
hcMcsNose,
hcMcsRightear,
hcMcsRighteye,
hcMcsUpperbody,
hcProfileface,
hcRighteye2splits,
hcSmile,
hcUpperbody
);
